openapi: 3.0.0
info:
  title: API Example
  description: >
    Example where there isn't a schema which can be diagrammed.
  version: '3.0'
paths:
  /users:
    get:
      summary: Returns a list of users.
      tags:
        - users
      responses:
        '200': 
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string